application:
  port: "8080"
  logPath: "log/server.log"
  logLevel: "debug"
storage:
  type: "s3"
  region: "us-east-2"
  bucket: "vasiliy-internal-test-bucket"
opt_srv:
  endpoint: "optimization-server"
  port: "8090"