run:
  timeout: 5m
  modules-download-mode: vendor
output:
  format: line-number
linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - varcheck
    - structcheck
    - govet
    - gocritic
    - typecheck
    - goconst
    - gocyclo
    - errcheck
    - bodyclose
    - deadcode
    - ifshort
    - misspell
    - noctx

  fast: false
linters-settings:
  gofmt:
    simplify: false
issues:
  exclude-use-default: false
  exclude-rules:
    - text: "writer.Write"
      linters:
        - errcheck
    - text: "body.Close"
      linters:
        - errcheck