apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.api.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.component.api.service.type }}
  selector:
    component: {{ .Values.component.api.name }}
  ports:
    - port: {{ .Values.component.api.service.port }}
      targetPort: {{ .Values.component.api.deployment.containerPort }}