apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.optimization.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.component.optimization.service.type }}
  selector:
    component: {{ .Values.component.optimization.name }}
  ports:
    - port: {{ .Values.component.optimization.service.port }}
      targetPort: {{ .Values.component.optimization.deployment.containerPort }}